INSERT INTO companies (id, name) VALUES
(1, "Microsoft Corporation"),
(2, "EcoWare"),
(3, "Apple Inc."),
(4, "Amazon.com Inc."),
(5, "Facebook Inc. Class A"),
(6, "Berkshire Hathaway Inc. Class B"),
(7, "Cekata LTD"),
(8, "SMG ltd"),
(9, "Arab & Funny corp."),
(10, "Pashaliev i sinove"),
(11, "JPMorgan Chase & Co."),
(12, "Visa Inc. Class A"),
(13, "Albanian Government"),
(14, "Intel Corporation"),
(15, "Verizon Communications Inc."),
(16, "Cisco Systems Inc."),
(17, "UnitedHealth Group Incorporated"),
(18, "Pfizer Inc."),
(19, "Chevron Corporation"),
(20, "AT&T Inc."),
(21, "Home Depot Inc."),
(22, "Mastercard Incorporated Class A"),
(23, "Merck & Co. Inc."),
(24, "Boeing Company"),
(25, "Walt Disney Company"),
(26, "Wells Fargo & Company"),
(27, "Comcast Corporation Class A"),
(28, "Coca-Cola Company"),
(29, "PepsiCo Inc."),
(30, "Netflix Inc."),
(31, "Citigroup Inc."),
(32, "McDonald's Corporation"),
(33, "Walmart Inc."),
(34, "Abbott Laboratories"),
(35, "Oracle Corporation"),
(36, "Philip Morris International Inc."),
(37, "Adobe Inc."),
(38, "International Business Machines Corporation"),
(39, "3M Company"),
(40, "PayPal Holdings Inc"),
(41, "AbbVie Inc."),
(42, "Union Pacific Corporation"),
(43, "salesforce.com inc."),
(44, "Medtronic plc"),
(45, "Amgen Inc."),
(46, "Broadcom Inc."),
(47, "Honeywell International Inc."),
(48, "NVIDIA Corporation"),
(49, "Accenture Plc Class A"),
(50, "Thermo Fisher Scientific Inc."),
(51, "Eli Lilly and Company"),
(52, "Costco Wholesale Corporation"),
(53, "United Technologies Corporation"),
(54, "NIKE Inc. Class B"),
(55, "Texas Instruments Incorporated"),
(56, "Altria Group Inc"),
(57, "Linde plc"),
(58, "Starbucks Corporation"),
(59, "Lowe's Companies Inc."),
(60, "NextEra Energy Inc."),
(61, "General Electric Company"),
(62, "Gilead Sciences Inc."),
(63, "DowDuPont Inc."),
(64, "American Tower Corporation"),
(65, "Danaher Corporation"),
(66, "Caterpillar Inc."),
(67, "Booking Holdings Inc."),
(68, "United Parcel Service Inc. Class B"),
(69, "Bristol-Myers Squibb Company"),
(70, "American Express Company"),
(71, "U.S. Bancorp"),
(72, "Anthem Inc."),
(73, "ConocoPhillips"),
(74, "Lockheed Martin Corporation"),
(75, "Mondelez International Inc. Class A"),
(76, "QUALCOMM Incorporated"),
(77, "Goldman Sachs Group Inc."),
(78, "Automatic Data Processing Inc."),
(79, "CVS Health Corporation"),
(80, "Intuit Inc."),
(81, "Becton Dickinson and Company"),
(82, "TJX Companies Inc"),
(83, "Celgene Corporation"),
(84, "Intuitive Surgical Inc."),
(85, "Duke Energy Corporation"),
(86, "Chubb Limited"),
(87, "Dominion Energy Inc"),
(88, "Cigna Corporation"),
(89, "Schlumberger NV"),
(90, "CME Group Inc. Class A"),
(91, "Charter Communications Inc. Class A"),
(92, "Stryker Corporation"),
(93, "Morgan Stanley"),
(94, "NPC Financial Services Group Inc."),
(95, "Colgate-Palmolive Company"),
(96, "CSX Corporation"),
(97, "Simon Property Group Inc."),
(98, "EOG Resources Inc."),
(99, "BlackRock Inc."),
(100, "Charles Schwab Corporation");

INSERT INTO investors (id, investor_name) VALUES
(1, "Bocheto"),
(2, "The All-Mighty Bull"),
(3, "Luis Miguel"),
(4, "Rumyana Laskina"),
(5, "Zosia Okiniehchshczcshhczcs"),
(6, "The lil Savani"),
(7, "Sacheto"),
(8, "Gjorcheto Pashalijski"),
(9, "Hajde be Deyan"),
(10, "Divanchester"),
(11, "Yoto Vpishe"),
(12, "Susama bin Laden"),
(13, "Hojlund"),
(14, "Jewish Dwarf"),
(15, "Roberto Carlos"),
(16, "Caroline Queen"),
(17, "Leo Pessi"),
(18, "Nina Nana Nona"),
(19, "Herr Getschev"),
(20, "Darwizzy"),
(21, "Gocheto"),
(22, "TE55"),
(23, "Nacheto"),
(24, "Mani Banani"),
(25, "Gosho ot Pochivka"),
(26, "Ana Paula Neves Ferreira los Marta de la Fuenta por Aguero Ronaldo Messi von Gruethenbuerg"),
(27, "Mimeto ot Varna"),
(28, "Ivo Nikolov"),
(29, "Kopeikata"),
(30, "Muhammad Iqbal"),
(31, "Kiro"),
(32, "Golqmata Savani"),
(33, "Sachko Vezenkov"),
(34, "Maicheto"),
(35, "Golqqqqqm"),
(36, "Nikotina"),
(37, "Noel Cosgrave"),
(38, "Adolf Hitler"),
(39, "Shaquille O Neill"),
(40, "Benito Mussolini"),
(41, "Franco"),
(42, "Bilal Bari"),
(43, "Turicov"),
(44, "Kiril Despodov"),
(45, "Bobi Atoma"),
(46, "Nestor el Maestro"),
(47, "Muhammad Ali"),
(48, "Prepi"),
(49, "Cristo Penaldo"),
(50, "Oscar D Leon"),
(51, "Héctor Lavoe"),
(52, "Frankie Ruiz"),
(53, "Willie Colón"),
(54, "Gilberto Santa Rosa"),
(55, "Eddie Santiago"),
(56, "Grupo Niche"),
(57, "Celia Cruz"),
(58, "Simón Díaz"),
(59, "Servando Primara"),
(60, "Chino y Nacho"),
(61, "Franco De Vita"),
(62, "Yordano"),
(63, "Yoni Pacheco"),
(64, "Pablo Milanés"),
(65, "Camarón de la Isla"),
(66, "Julio Iglesias"),
(67, "Julian Alvarez"),
(68, "Édith Piaf"),
(69, "Juanito Alimaña"),
(70, "Ricardo Montaner"),
(71, "Antonio Lauro"),
(72, "José Luis Rodríguez"),
(73, "Reynaldo Armas"),
(74, "Frank Quintero"),
(75, "Reina Lucero"),
(76, "Armando Molero"),
(77, "Osvaldo Torres"),
(78, "Jerry Rivera"),
(79, "José Alberto El Canario"),
(80, "El Gran Combo"),
(81, "Los Adolescentes"),
(82, "Maelo Ruiz"),
(83, "Joaquin Sabina"),
(84, "Victor Jara"),
(85, "Facundo Cabral"),
(86, "Violeta Parra"),
(87, "Mercedes Sosa"),
(88, "Caetano Veloso"),
(89, "Victor Heredia"),
(90, "Alfredo Zitarrosa"),
(91, "Manu Chao"),
(92, "Vicentico"),
(93, "El León Santillán"),
(94, "Diomedes Díaz"),
(95, "Rafael Orozco"),
(96, "El Binomio de Oro"),
(97, "Los Diablitos"),
(98, "Daniel Celedón"),
(99, "Shakira"),
(100, "Sofiq");